const CODE = {
  UNKNOWN: 9999,
  LOGIN: 1000,
  HTTP: 2000,
  HTTP_API: 2001,
  HTTP_API_USER_LOGIN: 2002,
  HTTP_API_USER_DETAIL: 2003,
  HTTP_API_USER_UPDATE: 2004,
  HTTP_API_TOTP_ALL: 2005,
  HTTP_API_TOTP_UPDATE_OR_CREATE: 2006,
  HTTP_API_TOTP_DELETE: 2007,

}

const MESSAGE = {
  [CODE.UNKNOWN]: '未知错误',
  [CODE.LOGIN]: '登录失败',
  [CODE.HTTP]: '网络请求失败',
  [CODE.HTTP_API]: '业务处理失败',
  [CODE.HTTP_API_USER_LOGIN]: '业务登录失败',
  [CODE.HTTP_API_USER_DETAIL]: '查询详情失败',
  [CODE.HTTP_API_USER_UPDATE]: '更新失败',
  [CODE.HTTP_API_TOTP_ALL]: '查询列表失败',
  [CODE.HTTP_API_TOTP_UPDATE_OR_CREATE]: '更新失败',
  [CODE.HTTP_API_TOTP_DELETE]: '删除失败',
}

export { CODE, MESSAGE }